### ISSUE TITLE
웹 주소 문의드립니다

### ISSUE THREAD

**Issue by iykkim** [SeongSikChae/PowerManagerServer#1]
안녕하세요.
먼저 좋은 프로그램 만들어 주셔서 감사드리며, 한 가지 문의 드립니다.
웹 브라우저로 PowerManagerServer에 접속하는 부분에서 정확히 주소를 어떻게 하면 되나요?
그냥 PowerManagerServer IP주소만 적으면 되는지, 아니면 http://[서버 IP주소]/ClientApp/build/index.html 이라고 해야 하는지 모르겠습니다.
두 가지 다 시도해봤지만 모두 연결 시간 초과 에러만 나오고 페이지가 열리지 않고 있으며, PowerManagerServer의 80, 443포트 등은 모두 열려있고 PowerManagerServer 프로세스도 잘 실행 중인 상태입니다.

**Comment by SeongSikChae** [comment]
https://서버IP주소/ 만 치면 Client 인증서를 선택하는 창이 뜨면서 클라이언트 인증서를 선택 후 확인을 하면 화면이 뜨게 됩니다.

만약 뜨지 않는다면 접속하는 PC에 루트인증서와 클라이언트 인증서가 정상적으로 등록된 상태인지 점검해보시기 바랍니다.

또한 서버에도 루트인증서가 정상적으로 등록된 상태인지 점검해보시기 바랍니다.

**Comment by SeongSikChae** [comment]
![4](https://user-images.githubusercontent.com/55735227/157872489-2fbc1d92-088e-43eb-935d-85e9e44553e7.png)

정상적이라면 이런식으로 나오게 될겁니다.

**Comment by iykkim** [comment]
답변 감사합니다.
우선 올려놓으신 ppt 매뉴얼을 서버를 구성한 Linux가 아닌 Windows용으로 받아서 보고 있던걸 알았고, Linux ppt로 다시 보고 있습니다.

그렇지만 인증서 생성, 설치는 동일하고 서버 설치, 실행 부분도 큰 차이가 없어서 구동한 상태는 문제가 없어 보였으나, 이번에 centOS Streamer8도 이 PowerManagerServer를 위해 새로 설치한 상태여서 기본 활성화된 방화벽을 비활성화한 후에 해보니 말씀하신대로 인증서 선택창이 나와서 선택하고 진행했습니다.

하지만 그 다음에는 "이 페이지가 작동하지 않습니다 (ERR_EMPTY_RESPONSE)"라고 나오고 초기 화면이 안 나오는데 어느 부분을 더 확인해 봐야 할까요?

PowerManager 프로세스는 ps 명령으로 잘 작동 중인건 확인되며, 구동전 초기 설정도 매뉴얼대로 다 해놓은 상태입니다.

참고로 config.yml 파일 내용은 아래와 같습니다.
(암호만 실제 내용에서 *로 표기했으며, AdminThumbprint 값은 매뉴얼에 따라 생성된 클라이언트 인증서인 "c.crt"의 지문값을 복사)

HttpPort: 80
HttpsPort: 443
ServerCertificate: /PowerManager/config/S.p12
ServerCertificatePassword: ********
MqttServerPort: 1803
DbPath: /PowerManager/data/PowerManager.sqlite
AdminThumbprint: 346b23af81cb865234cfa070da0d7dfd654f0bd6

**Comment by SeongSikChae** [comment]
log 경로에 PowerManagerServer.log 및 access.log 파일을 첨부해주시기 바라며 해당 로그에 다른 에러가 표시되어있는지 확인하시기 바랍니다.

**Comment by iykkim** [comment]
현재 서버만 구성 중인 상태라 접근 기록은 아직 아무 내용도 없는 0 byte여서 server.log 파일만 첨부했습니다.
에러로 보이는 내용은 없습니다.

[server.log](https://github.com/SeongSikChae/PowerManagerServer/files/8236835/server.log)

**Comment by SeongSikChae** [comment]
클라이언트 인증서를 정확히 선택하셨는지 확인해보시고 openssl로 클라이언트 인증서와 서버인증서가 유효한지 확인하시기 바랍니다 또한 브라우저에서 Control + Shift + R을 눌러서 캐시를 날려보시고 현재 브라우저가 무엇인지도 알려주시기 바랍니다.

**Comment by iykkim** [comment]
답변 감사합니다.

질문 후에 다시 보니 연결하는 Windows PC에서 클라이언트 인증서가 아닌 루트 인증서만 설치를 해 놓고 선택해서 생긴 상황으로 파악되었습니다. ^^;

클라이언트 인증서 c.crt 설치 후, 연결시 선택하자 초기 화면이 아래와 같이 잘 나오고 있습니다.

![image](https://user-images.githubusercontent.com/52940190/158000089-12f1f8d4-cea9-496d-8e33-05e9a24d2540.png)

답변 감사드리며, 다른 내용 진행 후 더 궁금한 사항이 생기면 다시 문의 드리겠습니다.

그럼 즐거운 주말 보내세요~

**Comment by SeongSikChae** [comment]
:)
